import { AppConfig } from "@/types/apps";

export const APPS: AppConfig[] = [
  {
    id: "finder",
    name: "Finder",
    icon: "/finder.png",
    description: "File browser",
    accentColor: "#007AFF",
    defaultPosition: { x: 80, y: 40 },
    defaultSize: { width: 900, height: 600 },
    minSize: { width: 600, height: 400 },
    menuBarTitle: "Finder",
    multiWindow: true,
    cascadeOffset: 30,
  },
  {
    id: "notes",
    name: "Notes",
    icon: "/notes.png",
    description: "Personal notes and thoughts",
    accentColor: "#FFCC00",
    defaultPosition: { x: 100, y: 50 },
    defaultSize: { width: 900, height: 600 },
    minSize: { width: 600, height: 400 },
    menuBarTitle: "Notes",
  },
  {
    id: "github",
    name: "GitHub",
    icon: "/github.svg",
    description: "Open Sanjiv's GitHub profile",
    accentColor: "#24292F",
    defaultPosition: { x: 100, y: 50 },
    defaultSize: { width: 900, height: 600 },
    minSize: { width: 600, height: 400 },
    menuBarTitle: "GitHub",
    externalUrl: "https://github.com/sanprab",
    showInFinderApplications: false,
  },
  {
    id: "google-chrome",
    name: "Google Chrome",
    icon: "/google-chrome.png",
    description: "Web browser",
    accentColor: "#4285F4",
    defaultPosition: { x: 100, y: 50 },
    defaultSize: { width: 900, height: 600 },
    minSize: { width: 600, height: 400 },
    menuBarTitle: "Google Chrome",
    dockStatic: true,
    showInFinderApplications: false,
  },
  {
    id: "x",
    name: "X",
    icon: "/x.svg",
    description: "Open Sanjiv's X profile",
    accentColor: "#000000",
    defaultPosition: { x: 100, y: 50 },
    defaultSize: { width: 900, height: 600 },
    minSize: { width: 600, height: 400 },
    menuBarTitle: "X",
    externalUrl: "https://x.com/snjvpr",
    dockIconScale: 0.88,
    showInFinderApplications: false,
  },
  {
    id: "notion",
    name: "Notion",
    icon: "/notion.png",
    description: "Workspace",
    accentColor: "#000000",
    defaultPosition: { x: 100, y: 50 },
    defaultSize: { width: 900, height: 600 },
    minSize: { width: 600, height: 400 },
    menuBarTitle: "Notion",
    dockStatic: true,
    showInFinderApplications: false,
  },
  {
    id: "sublime-text",
    name: "Sublime Text",
    icon: "/sublime-text.png",
    description: "Code editor",
    accentColor: "#FF9800",
    defaultPosition: { x: 100, y: 50 },
    defaultSize: { width: 900, height: 600 },
    minSize: { width: 600, height: 400 },
    menuBarTitle: "Sublime Text",
    dockStatic: true,
    showInFinderApplications: false,
  },
  {
    id: "codex",
    name: "Codex",
    icon: "/codex.png",
    description: "AI coding assistant",
    accentColor: "#10A37F",
    defaultPosition: { x: 100, y: 50 },
    defaultSize: { width: 900, height: 600 },
    minSize: { width: 600, height: 400 },
    menuBarTitle: "Codex",
    dockStatic: true,
    showInFinderApplications: false,
  },
  {
    id: "claude-code",
    name: "Claude Code",
    icon: "/claude-code.png",
    description: "AI coding assistant",
    accentColor: "#D97757",
    defaultPosition: { x: 100, y: 50 },
    defaultSize: { width: 900, height: 600 },
    minSize: { width: 600, height: 400 },
    menuBarTitle: "Claude Code",
    dockStatic: true,
    showInFinderApplications: false,
  },
  {
    id: "maps",
    name: "Maps",
    icon: "/maps.png",
    description: "Maps and directions",
    accentColor: "#007AFF",
    defaultPosition: { x: 100, y: 50 },
    defaultSize: { width: 900, height: 600 },
    minSize: { width: 600, height: 400 },
    menuBarTitle: "Maps",
    dockStatic: true,
    dockIconScale: 1.14,
    showInFinderApplications: false,
  },
  {
    id: "copilot-money",
    name: "Copilot Money",
    icon: "/copilot-money.png",
    description: "Personal finance",
    accentColor: "#56B682",
    defaultPosition: { x: 100, y: 50 },
    defaultSize: { width: 900, height: 600 },
    minSize: { width: 600, height: 400 },
    menuBarTitle: "Copilot Money",
    dockStatic: true,
    showInFinderApplications: false,
  },
  {
    id: "messages",
    name: "Messages",
    icon: "/messages.png",
    description: "Chat with AI personas",
    accentColor: "#34C759",
    defaultPosition: { x: 150, y: 80 },
    defaultSize: { width: 800, height: 550 },
    minSize: { width: 500, height: 400 },
    menuBarTitle: "Messages",
    showOnDockByDefault: false,
    showOnDockWhenOpen: false,
  },
  {
    id: "photos",
    name: "Photos",
    icon: "/photos.png",
    description: "Photo library",
    accentColor: "#FF6B6B",
    defaultPosition: { x: 130, y: 60 },
    defaultSize: { width: 900, height: 650 },
    minSize: { width: 600, height: 450 },
    menuBarTitle: "Photos",
  },
  {
    id: "music",
    name: "Spotify",
    icon: "/spotify.png",
    description: "Spotify music library",
    accentColor: "#1ED760",
    defaultPosition: { x: 140, y: 70 },
    defaultSize: { width: 900, height: 650 },
    minSize: { width: 600, height: 450 },
    menuBarTitle: "Spotify",
  },
  {
    id: "calendar",
    name: "Calendar",
    icon: "/calendar.png",
    description: "Calendar and events",
    accentColor: "#FF3B30",
    defaultPosition: { x: 170, y: 60 },
    defaultSize: { width: 900, height: 700 },
    minSize: { width: 700, height: 500 },
    menuBarTitle: "Calendar",
  },
  {
    id: "weather",
    name: "Weather",
    icon: "/weather.png",
    description: "Weather forecast",
    accentColor: "#0A7CFF",
    defaultPosition: { x: 220, y: 90 },
    defaultSize: { width: 780, height: 560 },
    minSize: { width: 560, height: 420 },
    menuBarTitle: "Weather",
    showOnDockByDefault: false,
    mobile: {
      supported: false,
      shellFallbackAppId: "notes",
      directRouteRedirectTo: "/",
      showInFinderApplications: false,
    },
  },
  {
    id: "iterm",
    name: "iTerm",
    icon: "/iterm.png",
    description: "Terminal emulator",
    accentColor: "#00D455",
    defaultPosition: { x: 120, y: 70 },
    defaultSize: { width: 800, height: 500 },
    minSize: { width: 500, height: 300 },
    menuBarTitle: "iTerm",
  },
  {
    id: "settings",
    name: "Settings",
    icon: "/settings.png",
    description: "System preferences",
    accentColor: "#8E8E93",
    defaultPosition: { x: 200, y: 100 },
    defaultSize: { width: 900, height: 600 },
    minSize: { width: 700, height: 400 },
    menuBarTitle: "System Settings",
  },
  {
    id: "textedit",
    name: "TextEdit",
    icon: "/textedit.png",
    description: "Plain text editor",
    accentColor: "#8E8E93",
    defaultPosition: { x: 160, y: 90 },
    defaultSize: { width: 700, height: 500 },
    minSize: { width: 400, height: 300 },
    menuBarTitle: "TextEdit",
    showOnDockByDefault: false,
    mobile: {
      supported: false,
      shellFallbackAppId: "finder",
      directRouteRedirectTo: "/",
      showInFinderApplications: false,
    },
    multiWindow: true,
    cascadeOffset: 30,
  },
  {
    id: "preview",
    name: "Preview",
    icon: "/preview.png",
    description: "Image and PDF viewer",
    accentColor: "#007AFF",
    defaultPosition: { x: 180, y: 100 },
    defaultSize: { width: 800, height: 600 },
    minSize: { width: 400, height: 300 },
    menuBarTitle: "Preview",
    showOnDockByDefault: false,
    mobile: {
      supported: false,
      shellFallbackAppId: "finder",
      directRouteRedirectTo: "/",
      showInFinderApplications: false,
    },
    multiWindow: true,
    cascadeOffset: 30,
  },
];

export function getAppById(id: string): AppConfig | undefined {
  return APPS.find((app) => app.id === id);
}

export function getAppIds(): string[] {
  return APPS.map((app) => app.id);
}
